title: napari-splitmask
author: Ana Stojiljkovic and Guillaume Witz
logo: ![logo](../images/napari-splitmask_logo.png)

execute:
  execute_notebooks: 'off'

sphinx:
  config:
    html_extra_path: ['.','images']