title: napari-splitmask
author: Ana Stojiljkovic and Guillaume Witz
logo: docs/images/napari-splitmask_logo.png

execute:
  execute_notebooks: 'off'

sphinx:
  config:
    html_extra_path: ['.','docs/images']